---
- name: Mmanage Virtual Machine power state
  hosts: localhost
  tasks:
    - name: Get an existing Virtual Machines
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ vm_namespace }}"
      register: VM_machines
      
    - name: List all Virtual Machines 
      ansible.builtin.debug:
        var: VM_machines.resources
        
    - name: change virtual machine running to {{ state }}
      kubernetes.core.k8s:
        state: patched
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        merge_type: strategic-merge
        definition:  
          spec:
            running: "{{ vm_state }}"
