---
- name: Mmanage Virtual Machine power state
  hosts: localhost
  tasks:
    - name: change virtual machine running to {{ state }}
      kubernetes.core.k8s:
        merge_type: "merge"
        namespace: "{{ vm_namespace }}"
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            namespace: "{{ vm_namespace }}"
            #name: "{{ vm_name }}"
          spec:
            running: "{{ vm_state }}"
