---
- name: Mmanage Virtual Machine power state
  hosts: localhost
  tasks:
    - name: Get an existing Virtual Machines
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ vm_namespace }}"
      register: VM_machines
    - name: List all Virtual Machines 
      ansible.builtin.debug:
        var: VM_machines
        
    - name: change virtual machine running to {{ state }}
      kubernetes.core.k8s:
        merge_type: "merge"
        namespace: "{{ vm_namespace }}"
        definition:
          api_version: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            namespace: "{{ vm_namespace }}"
            #name: "{{ vm_name }}"
          spec:
            running: "{{ vm_state }}"
