---
- name: Toggle VMs based on desired state
  hosts: localhost
  gather_facts: false
  vars:
    desired_vm_state: false  # Set to true to start, false to stop

  tasks:

    - name: Get all VirtualMachines in all namespaces
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
      register: vm_facts

    - name: Filter VMs that need toggling
      set_fact:
        vms_to_toggle: >-
          {{
            vm_facts.resources | selectattr('spec.running', 'defined') |
            selectattr('spec.running', 'ne', desired_vm_state) |
            list
          }}

    - name: Toggle VM state
      kubernetes.core.k8s:
        state: present
        resource_definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            running: "{{ desired_vm_state }}"
      loop: "{{ vms_to_toggle }}"
      loop_control:
        label: "{{ item.metadata.namespace }}/{{ item.metadata.name }}"
