---
- name: Toggle VMs in a specific namespace
  hosts: localhost
  gather_facts: false
  vars:
    target_namespace: default         # 👈 Replace or override via -e
    desired_vm_state: false                # true = start, false = stop

  tasks:

    - name: Get VirtualMachines in the target namespace
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ target_namespace }}"
      register: vm_facts

    - name: Debug
      ansible.builtin.debug:
        var: vm_facts.resources
    - name: Filter VMs that need toggling
      set_fact:
        vms_to_toggle: >-
          {{
            vm_facts.resources | selectattr('spec.running', 'defined') |
            selectattr('spec.running', 'ne', desired_vm_state) |
            list
          }}

    - name: Toggle VM state in {{ target_namespace }}
      kubernetes.core.k8s:
        state: present
        resource_definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ target_namespace }}"
          spec:
            running: "{{ desired_vm_state }}"
      loop: "{{ vms_to_toggle }}"
      loop_control:
        label: "{{ item.metadata.name }}"
