---
- name: Mmanage Virtual Machine power state
  hosts: localhost
  tasks:
    - name: Get an existing Virtual Machines
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ vm_namespace }}"
      register: VM_machines
        
    - name: change virtual machine running to {{ state }}
      kubernetes.core.k8s:
        state: present
        resource_definition:
          api_version: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
          spec:
            running: "{{ vm_state }}"
